### ISSUE TITLE
resolve aruco-opencv dependency issue

### ISSUE THREAD

**Issue by dylan-gonzalez** [MonashNovaRover/nova#106]
**CONTEXT**
Seems like [this](https://github.com/MonashNovaRover/nixfiles/blob/99df88b799d89f8b99efb4434e23e322f873df84/overlay/ros/maintanence.nix#L230-L266) is not needed anymore?
- https://github.com/fictionlab/ros_aruco_opencv/pull/34

**TODO**
- Resolve aruco-opencv dependency issue with OpenCV 4.7.0+

**Comment by V01DBREAKER** [comment]
Resolved in [this](https://github.com/MonashNovaRover/nixfiles/commit/8f3bba42ba12fbee458ef14601c256a890ed27df) commit
