### ISSUE TITLE
Start CAN on boot

### ISSUE THREAD

**Issue by dylan-gonzalez** [MonashNovaRover/nova#136]
**CONTEXT**
On branch `feature/start-can`. 
- The nix user will need to be logged in by default on Ubuntu
- Simply starting the script doesn't work, but starting a basic hello-world script works

**Comment by Redecorating** [comment]
[Here on notion](https://www.notion.so/Running-the-Rover-1798893f956c40a4a4330e1d555f2b34#23363d6d5cc7474fb808d7dbd5e209da) it only says can is not started on boot for J3. Is this only the case for J3 or are J1 and J2 impacted too?

**Comment by dylan-gonzalez** [comment]
J1 - can starts on boot
J2 - not sure
J3 - can does not start on boot

**Comment by Redecorating** [comment]
/home/nvidia/nova_ws/src/rover/core/systemctl/can.sh is missing from j3, but on j1 this is just a script that calls the main can script twice, so i modified the can.service on j3 to do it directly. Starting can on boot was working as is on j1 and j2 so I haven't modified those.

if can stops starting on boot on j1 or j2, you can try editing can.service so it looks like this:
```
$ cat /etc/systemd/system/can.service 
[Unit]
Description=Runs can start for can0 and can1 on startup
Requires=network-online.target network.target local-fs.target
After=network-online.target network.target local-fs.target

[Service]
User=root
Group=sudo
Type=oneshot
ExecStart=/home/nvidia/.nix-profile/bin/can start can0
ExecStart=/home/nvidia/.nix-profile/bin/can start can1
TimeoutStartSec=5
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by dylan-gonzalez** [comment]
The point of this was to do this with nix though using home-manager - any progress there? `feature/start-can` is an attempt at this

**Comment by Redecorating** [comment]
to do that on the jetsons i think we'd need to enable automatic login as you said, and probably passwordless sudo for at least the commands can.sh runs with sudo.

I can try to set it up like this, however I was thinking that once we start using the Orin's, which have nixOS not just ubuntu with user level nix, we can get nixOS to set up a system level systemd service (so same as what we currently have on the jetsons but it is managed by nix).

Of course, i would expect the home manager approach to work just as well on the orins as it would on the jetsons, but in the long term i would think that it's better to manage can at a system level unless we are wanting to put as much as possible in the home manager config opposed to the system nixos config.

**Comment by Redecorating** [comment]
In the software meeting today we decided to set this up by manually creating the systemd service files on the jetsons, and when we set up the orin nano's we will get nixOS to set up the systemd service automatically.
