### ISSUE TITLE
improve rover suspension and model in gazebo

### ISSUE THREAD

**Issue by vic-bart** [MonashNovaRover/nova#55]
**CONTEXT**
The rover's suspensions in gazebo is currently static (which isn't very accurate), and should be changed to dynamic (which would require closed kinematic chains, CKCs). 
The current file format defining the rover model in gazebo, URDF, doesn't support CKCs, but another file format, SDF, does (interesting fact: gazebo actually works with SDFs under-the-hood; URDFs are converted into SDFs before being used by gazebo).
The rover itself has changed significantly since the original URDF was made, so this would also entail a redesign of the rover's entire model.
- [SDF guide](https://sdformat.org/)
- [OnShape-to-URDF/SDF](https://onshape-to-robot.readthedocs.io/en/latest/)
  - Tried this, didn't work
- [SolidWorks-to-URDF](https://wiki.ros.org/sw_urdf_exporter)
  - What we've used before; could be used to create URDF and converted to SDF by hand (very tedious)

**TODO**
- Get up-to-date rover model from OnShape
- Export to SDF, or URDF (then convert to SDF)
- Fine tune SDF parameters to have accurate rover suspension

**Comment by ecthelion99** [comment]
Pretty sure Gazebo Harmonic (which we are planning to switch to) does not support closed kinematic chains. Generally the alternative is to use a plugin like [this](https://github.com/LeoRover/leo_simulator-ros2/blob/ros2/leo_gz_plugins%2Fsrc%2Fdifferential_system.cpp)

**Comment by vic-bart** [comment]
I'll also add [this](https://github.com/gazebosim/gz-physics/issues/25) here for reference
