### ISSUE TITLE
identify ROS topics needed from gazebo

### ISSUE THREAD

**Issue by vic-bart** [MonashNovaRover/nova#95]
**CONTEXT**
Gazebo Classic plugins published to ROS topics by default, but Gazebo Harmonic plugins do not &mdash; instead publishing to "Gazebo topics" on an internal Gazebo network that are not exposed to the ROS network. 
For these topics to be published as ROS topics, a "bridge" that maps Gazebo topics to ROS topics needs to be created using "ros_gz_bridge" (see resources for more).

**TODO**
- Join #gazebo-harmonic on slack (if you haven't already)
- Identify the ROS topics that need to be published from Gazebo

**RESOURCES**
- [gz integration with ros via ros_gz_bridge](https://gazebosim.org/docs/latest/ros2_integration/)

**Comment by V01DBREAKER** [comment]
https://monashnovarover.slack.com/archives/C07Q35T73V5/p1731566527106569
Working except depth camera now?
