### ISSUE TITLE
figure out why rviz nav2 plugins brokey

### ISSUE THREAD

**Issue by vic-bart** [MonashNovaRover/nova#96]
**CONTEXT**
The migration to Gazebo Harmonic has broken the nav2 plugins for rviz. Why? That's for you to find out!

**TODO**
- Identify which rviz nav2 plugins broke
- Identify why they broke

**RESOURCES**

**Comment by V01DBREAKER** [comment]
Attempted here: https://www.notion.so/Figure-out-why-rviz-nav2-plugins-are-brokey-3f104d21bc9c4881ba702ab44a1cbfdf

**Comment by vic-bart** [comment]
(backing up Notion page here in case it gets deleted)
**What is the problem?**
![image](https://github.com/user-attachments/assets/0651970f-b1b2-4a82-a9a5-9af096c623cd)
nav2_rviz_plugins related things will not load in rviz

**How to test?**
Run `ros2 launch auto_bringup rviz.launch.py` 

**Problem?**
Symbol `CostmapCostTool::updateAutoDeactivate` function is not defined

**Version issue?**
Nav2 Version: 1.3.2 (latest as of writing: 1.3.3)
Correct for Jazzy
rviz2 Version: 14.1.5
Latest for jazzy as of time of writing
No issues in the two commits to nav2_rviz_plugins relating to this problem

**File issue?** 
No, `/nix/store/<hash>/lib/libnav2_rviz_plugins.so` does exist at the correct location

**Migration issue?**
- https://docs.nav2.org/migration/Humble.html
- https://docs.nav2.org/migration/Iron.html 
No mention of issue or changes in the plugins from migraton docs

**Is it just due to the original .rviz file?**
![image](https://github.com/user-attachments/assets/8c35edfb-4204-49c7-a79e-fc734a080702)
(Same error msg)
Checking the token
![image](https://github.com/user-attachments/assets/eb24bc53-87f4-424c-881b-4e5b72f9de0c)
`CostmapCostTool::updateAutoDeactivate` is defined in the hpp as a private Q_SLOT but is not defined in the cpp
This problem is not in their humble branch as the file does not exist:
![image](https://github.com/user-attachments/assets/74106273-9d6b-473a-8841-f053382816a9)

**Proposed solution:** 
Remove all references to the method `updateAutoDeactivate()`  as it is currently not implemented or present in the cpp file.
Fixed by removing the symbol `updateAutoDeactivate` from both the header and code files during the postPatch phase in maintainence.nix
![image](https://github.com/user-attachments/assets/24df50e5-d022-401b-9bd2-c9387d936b0f)

**Related docs:**
- [nav2_rviz_plugins package page](https://index.ros.org/p/nav2_rviz_plugins/#jazzy-deps)
- [The code file](https://github.com/ros-navigation/navigation2/commits/main/nav2_rviz_plugins/src/costmap_cost_tool.cpp)
- [Same but different issue?](https://github.com/moveit/moveit_calibration/pull/61)

**Summary:**
- All plugins from nav2_rviz_plugins are currently broken as the plugin itself will not load.
- Issue seems to have been caused by migration from humble to jazzy somehow
- Fixed by removing the symbol `updateAutoDeactivate` from both the header and code files during the postPatch phase in maintainence.nix
